
#include <linux/types.h>
#include "defs.h"
struct sfilter sfilters[] = {
	{1, {"media.admob.com" } }, 
 	{1, {"/gampad/ads" } }, 
 	{1, {".checkm8.com/adam/" } }, 
 	{1, {"pagead2.googlesyndication.com" } }, 
 	{1, {"googleads.g.doubleclick.net/pageads/ads" } }, 
 	{1, {"xads.zedo.com/ads2/" } }, 
 	{1, {"xads.zedo.com/ads/" } }, 
 	{2, {"ad","doubleclick.net/" } }, 
 	{1, {"ad.yieldmanager.com/" } }, 
 	{1, {"ads.ad-center.com/" } }, 
 	{1, {"adsbygoogle.js" } }, 
 	{1, {"yimg.com/gs/apex/mediastore/" } }, 
 	{2, {"yimg.com","/dianominewwidget2.html" } }, 
 	{2, {"yimg.com","/quickplay_maxwellhouse.png" } }, 
 	{2, {"yimg.com","/sponsored.js" } }, 
 	{2, {"yimg.com","_skin_" } }, 
 	{2, {"google.com/jsapi?autoload=","ads" } }, 
 	{1, {"youtube-mp3.org/acode/" } }, 
 	{1, {"youtube.com/yva_video?adformat" } }, 
 	{2, {"s.ytimg.com/yts/swfbin/player-","/watch_as3.swf" } }, 
 	{1, {"youtube.com/yt/advertise/medias/images/" } }, 
 	{1, {"youtube.com/yt/css/www-advertise.css" } }, 
 	{2, {"youtube.com","_adsense_" } }, 
 	{3, {"ytimg.com/yts/img/channels/","_banner-",".jpg" } }, 
 	{3, {"ytimg.com/yts/img/channels/","_banner-",".png" } }, 
 	{2, {"ytimg.com","/channels4_banner.jpg" } }, 
 	{2, {"ytimg.com","/channels4_banner_hd.jpg" } }, 
 	{2, {"ytimg.com","/new_watch_background.jpg?" } }, 
 	{3, {"ytimg.com","/new_watch_background_",".jpg" } }, 
 	{2, {"ytimg.com","_banner$domain=youtube.com" } }, 
 	{1, {"/yahoo-ad-" } }, 
 	{1, {"/yahoo-ads/" } }, 
 	{1, {"/yahoo/ads." } }, 
 	{1, {"/yahoo_overture." } }, 
 	{1, {"/YahooAd_" } }, 
 	{1, {"/yahooads." } }, 
 	{1, {"/yahooads/" } }, 
 	{1, {"/yahooadsapi." } }, 
 	{1, {"/yahooadsobject." } }, 
 	{1, {"partnerads.ysm.yahoo.com" } }, 
 	{1, {"partnerads1.ysm.yahoo.com" } }, 
 	{1, {"yimg.com/ao/adv/" } }, 
 	{1, {"yimg.com/cv/ae/ca/audience/" } }, 
 	{1, {"yimg.com/cv/ae/us/audience/" } }, 
 	{2, {"yimg.com/cv/eng/",".webm" } }, 
 	{2, {"yimg.com/cv/eng/","/635x100_" } }, 
 	{2, {"yimg.com/cv/eng/","/970x250_" } }, 
 	{2, {"yimg.com/dh/ap/default/","/skins_" } }, 
 	{2, {"yimg.com/hl/ap/","_takeover_" } }, 
 	{2, {"yimg.com/hl/ap/default/","_background" } }, 
 	{1, {"yimg.com/i/i/de/cat/yahoo.html" } }, 
 	{1, {"yimg.com/la/i/wan/widgets/wjobs/" } }, 
 	{1, {"yimg.com/rq/darla/" } }, 
 	{2, {"yimg.com","/billboardv2r5min.js" } }, 
 	{2, {"yimg.com","/darla-secure-pre-min.js" } }, 
 	{2, {"yimg.com","/fairfax/$image" } }, 
 	{2, {"yimg.com","/flash/promotions/" } }, 
 	{2, {"yimg.com","/ya-answers-dmros-ssl-min.js" } }, 
 	{2, {"yimg.com","/yad*.js" } }, 
 	{2, {"yimg.com","/yad.html" } }, 
 	{2, {"yimg.com","/yfpadobject.js" } }, 
 	{2, {"yimg.com","_east.swf" } }, 
 	{2, {"yimg.com","_north.swf" } }, 
 	{2, {"yimg.com","_west.swf" } }, 
 
};
size_t num_sfilters = sizeof(sfilters) / sizeof(sfilters[0]);
